// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkEkcvqHRZe5wUMMcQNhxMV8AJv3apOME',
    appId: '1:265812990646:web:0e3992daa139207751a417',
    messagingSenderId: '265812990646',
    projectId: 'clasificador-basuras-7e8ea',
    authDomain: 'clasificador-basuras-7e8ea.firebaseapp.com',
    storageBucket: 'clasificador-basuras-7e8ea.appspot.com',
    measurementId: 'G-E3N184592T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAilPdabuQVx8mYgwciROFQdSaCikl7il0',
    appId: '1:265812990646:android:0efbf1900db739d051a417',
    messagingSenderId: '265812990646',
    projectId: 'clasificador-basuras-7e8ea',
    storageBucket: 'clasificador-basuras-7e8ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ke0v2jWuoQzkr0I6yy1aIupVVbBxVng',
    appId: '1:265812990646:ios:3d069ed04da10df351a417',
    messagingSenderId: '265812990646',
    projectId: 'clasificador-basuras-7e8ea',
    storageBucket: 'clasificador-basuras-7e8ea.appspot.com',
    iosClientId: '265812990646-m0r4auv5as0fu8310u618iri0ducrt35.apps.googleusercontent.com',
    iosBundleId: 'com.example.clasificadorBasuras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ke0v2jWuoQzkr0I6yy1aIupVVbBxVng',
    appId: '1:265812990646:ios:9c12764e9b07202451a417',
    messagingSenderId: '265812990646',
    projectId: 'clasificador-basuras-7e8ea',
    storageBucket: 'clasificador-basuras-7e8ea.appspot.com',
    iosClientId: '265812990646-1tmmo9kf5b8f2deaqinanj1hdb5ep3nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.clasificadorBasuras.RunnerTests',
  );
}
